<template>
  <div>
    <BackTop element="main" />
    <Collapse class="collapseComponent">
      <Card class="card" name="extra" :title="$t('Router.IconUi')">
        <Space wrap size="large">
          <Icon type="sync" />
          <Icon type="sync" size="25" />
          <Icon type="sync" size="30" color="#906eb5" />
          <Icon type="sync" spin size="25" />
        </Space>
      </Card>
      <Panel :title="$t('Card.NoInformationTemporarily')" key="1"> </Panel>
    </Collapse>
    <!--  -->
    <div class="iconBox">
      <div class="searchBox">
        <Input
          @change="searchIconVal"
          class="input"
          type="text"
          v-model="searchText"
          placeholder="请输入图标名称..."
        />
        <RadioGroup
          @change="iconTypeChange"
          class="radioGroup"
          v-model="iconType"
        >
          <RadioButton value="Filled" label="Filled" />
          <RadioButton value="Outhline" label="Outhline" />
        </RadioGroup>
      </div>
      <div class="iconList">
        <!-- <Space :size="[20, 20]" wrap> -->
        <div
          v-for="(icon, index) in icon"
          @click="copeIcon(icon)"
          :key="index"
          class="icon"
        >
            <Icon class="iconFont" :type="icon" size="36"></Icon>
            <p class="iconName">{{ icon }}</p>
        </div>
        <!-- </Space> -->
      </div>
    </div>
  </div>
</template>
<script>
import { debounce } from "@/utils/tool";
export default {
  data() {
    return {
      iconType: "Filled",
      searchText: "",
      icon: [],
      allIcon: [
        "accessibility",
        "add-circle",
        "add",
        "airplane",
        "alarm",
        "albums",
        "alert-circle",
        "alert",
        "american-football",
        "analytics",
        "aperture",
        "apps",
        "archive",
        "arrow-back-circle",
        "arrow-back",
        "arrow-down-circle",
        "arrow-down",
        "arrow-forward-circle",
        "arrow-forward",
        "arrow-redo-circle",
        "arrow-redo",
        "arrow-undo-circle",
        "arrow-undo",
        "arrow-up-circle",
        "arrow-up",
        "at-circle",
        "at",
        "attach",
        "backspace",
        "bag-add",
        "bag-check",
        "bag-handle",
        "bag-remove",
        "bag",
        "balloon",
        "ban",
        "bandage",
        "bar-chart",
        "barbell",
        "barcode",
        "baseball",
        "basket",
        "basketball",
        "battery-charging",
        "battery-dead",
        "battery-full",
        "battery-half",
        "beaker",
        "bed",
        "beer",
        "bicycle",
        "bluetooth",
        "boat",
        "body",
        "bonfire",
        "book",
        "bookmark",
        "bookmarks",
        "bowling-ball",
        "briefcase",
        "browsers",
        "brush",
        "bug",
        "build",
        "bulb",
        "bus",
        "business",
        "cafe",
        "calculator",
        "calendar-clear",
        "calendar-number",
        "calendar",
        "call",
        "camera-reverse",
        "camera",
        "car-sport",
        "car",
        "card",
        "caret-back-circle",
        "caret-back",
        "caret-down-circle",
        "caret-down",
        "caret-forward-circle",
        "caret-forward",
        "caret-up-circle",
        "caret-up",
        "cart",
        "cash",
        "cellular",
        "chatbox-ellipses",
        "chatbox",
        "chatbubble-ellipses",
        "chatbubble",
        "chatbubbles",
        "checkbox",
        "checkmark-circle",
        "checkmark-done-circle",
        "checkmark-done",
        "checkmark",
        "chevron-back-circle",
        "chevron-back",
        "chevron-double-back",
        "chevron-double-forward",
        "chevron-down-circle",
        "chevron-down",
        "chevron-forward-circle",
        "chevron-forward",
        "chevron-up-circle",
        "chevron-up",
        "clipboard",
        "close-circle",
        "close",
        "cloud-circle",
        "cloud-done",
        "cloud-download",
        "cloud-offline",
        "cloud-upload",
        "cloud",
        "cloudy-night",
        "cloudy",
        "code-download",
        "code-slash",
        "code-working",
        "code",
        "cog",
        "color-fill",
        "color-filter",
        "color-palette",
        "color-wand",
        "compass",
        "construct",
        "contract",
        "contrast",
        "copy",
        "create",
        "crop",
        "cube",
        "cut",
        "desktop",
        "diamond",
        // "dice",
        // "disc",
        // "document-attach",
        // "document-lock",
        // "document-text",
        // "document",
        // "documents",
        // "download",
        // "duplicate",
        // "ear",
        // "earth",
        // "easel",
        // "egg",
        // "ellipse",
        // "ellipsis-horizontal-circle",
        // "ellipsis-horizontal",
        // "ellipsis-vertical-circle",
        // "ellipsis-vertical",
        // "enter",
        // "exit",
        // "expand",
        // "extension-puzzle",
        // "eye-off",
        // "eye",
        // "eyedrop",
        // "fast-food",
        // "female",
        // "file-tray-full",
        // "file-tray-stacked",
        // "file-tray",
        // "film",
        // "filter-circle",
        // "filter",
        // "finger-print",
        // "fish",
        // "fitness",
        // "flag",
        // "flame",
        // "flash-off",
        // "flash",
        // "flashlight",
        // "flask",
        // "flower",
        // "folder-open",
        // "folder",
        // "football",
        // "footsteps",
        // "funnel",
        // "game-controller",
        // "gift",
        // "git-branch",
        // "git-commit",
        // "git-compare",
        // "git-merge",
        // "git-network",
        // "git-pull-request",
        // "glasses",
        // "globe",
        // "golf",
        // "grid",
        // "hammer",
        // "hand-left",
        // "hand-right",
        // "happy",
        // "hardware-chip",
        // "headset",
        // "heart-circle",
        // "heart-dislike-circle",
        // "heart-dislike",
        // "heart-half",
        // "heart",
        // "help-buoy",
        // "help-circle",
        // "help",
        // "home",
        // "hourglass",
        // "ice-cream",
        // "id-card",
        // "image",
        // "images",
        // "infinite",
        // "information-circle",
        // "information",
        // "invert-mode",
        // "journal",
        // "key",
        // "keypad",
        // "language",
        // "laptop",
        // "layers",
        // "leaf",
        // "library",
        // "link",
        // "list-circle",
        // "list",
        // "locate",
        // "location",
        // "lock-closed",
        // "lock-open",
        // "log-in",
        // "log-out",
        // "logo-alipay",
        // "logo-amazon",
        // "logo-amplify",
        // "logo-android",
        // "logo-angular",
        // "logo-apple-appstore",
        // "logo-apple-ar",
        // "logo-apple",
        // "logo-behance",
        // "logo-bitbucket",
        // "logo-bitcoin",
        // "logo-buffer",
        // "logo-capacitor",
        // "logo-chrome",
        // "logo-closed-captioning",
        // "logo-codepen",
        // "logo-css3",
        // "logo-designernews",
        // "logo-deviantart",
        // "logo-discord",
        // "logo-docker",
        // "logo-dribbble",
        // "logo-dropbox",
        // "logo-edge",
        // "logo-electron",
        // "logo-euro",
        // "logo-facebook",
        // "logo-figma",
        // "logo-firebase",
        // "logo-firefox",
        // "logo-flickr",
        // "logo-foursquare",
        // "logo-gitee",
        // "logo-github",
        // "logo-gitlab",
        // "logo-google-playstore",
        // "logo-google",
        // "logo-hackernews",
        // "logo-html5",
        // "logo-instagram",
        // "logo-ionic",
        // "logo-ionitron",
        // "logo-javascript",
        // "logo-kui",
        // "logo-laravel",
        // "logo-linkedin",
        // "logo-markdown",
        // "logo-mastodon",
        // "logo-medium",
        // "logo-microsoft",
        // "logo-no-smoking",
        // "logo-nodejs",
        // "logo-npm",
        // "logo-octocat",
        // "logo-paypal",
        // "logo-pinterest",
        // "logo-playstation",
        // "logo-pwa",
        // "logo-python",
        // "logo-react",
        // "logo-reddit",
        // "logo-rss",
        // "logo-sass",
        // "logo-skype",
        // "logo-slack",
        // "logo-snapchat",
        // "logo-soundcloud",
        // "logo-stackoverflow",
        // "logo-steam",
        // "logo-stencil",
        // "logo-tableau",
        // "logo-telegram",
        // "logo-tiktok",
        // "logo-tumblr",
        // "logo-tux",
        // "logo-twitch",
        // "logo-twitter",
        // "logo-usd",
        // "logo-venmo",
        // "logo-vercel",
        // "logo-vimeo",
        // "logo-vk",
        // "logo-vue",
        // "logo-web-component",
        // "logo-wechat",
        // "logo-whatsapp",
        // "logo-windows",
        // "logo-wordpress",
        // "logo-xbox",
        // "logo-xing",
        // "logo-yahoo",
        // "logo-yen",
        // "logo-youtube",
        // "magnet",
        // "mail-open",
        // "mail-unread",
        // "mail",
        // "male-female",
        // "male",
        // "man",
        // "map",
        // "medal",
        // "medical",
        // "medkit",
        // "megaphone",
        // "menu",
        // "mic-circle",
        // "mic-off-circle",
        // "mic-off",
        // "mic",
        // "moon",
        // "move",
        // "musical-note",
        // "musical-notes",
        // "navigate-circle",
        // "navigate",
        // "newspaper",
        // "notifications-circle",
        // "notifications-off-circle",
        // "notifications-off",
        // "notifications",
        // "nuclear",
        // "nutrition",
        // "open",
        // "options",
        // "paper-plane",
        // "partly-sunny",
        // "pause-circle",
        // "pause",
        // "paw",
        // "pencil",
        // "people-circle",
        // "people",
        // "person-add",
        // "person-circle",
        // "person-remove",
        // "person",
        // "phone-landscape",
        // "phone-portrait",
        // "pie-chart",
        // "pin",
        // "pint",
        // "pizza",
        // "planet",
        // "play-back-circle",
        // "play-back",
        // "play-circle",
        // "play-forward-circle",
        // "play-forward",
        // "play-skip-back-circle",
        // "play-skip-back",
        // "play-skip-forward-circle",
        // "play-skip-forward",
        // "play",
        // "podium",
        // "power",
        // "pricetag",
        // "pricetags",
        // "print",
        // "prism",
        // "pulse",
        // "push",
        // "qr-code",
        // "radio-button-off",
        // "radio-button-on",
        // "radio",
        // "rainy",
        // "reader",
        // "receipt",
        // "recording",
        // "refresh-circle",
        // "refresh",
        // "reload-circle",
        // "reload",
        // "remove-circle",
        // "remove",
        // "reorder-four",
        // "reorder-three",
        // "reorder-two",
        // "repeat",
        // "resize",
        // "restaurant",
        // "return-down-back",
        // "return-down-forward",
        // "return-up-back",
        // "return-up-forward",
        // "ribbon",
        // "rocket",
        // "rose",
        // "sad",
        // "save",
        // "scale",
        // "scan-circle",
        // "scan",
        // "school",
        // "search-circle",
        // "search",
        // "send",
        // "server",
        // "settings",
        // "shapes",
        // "share-social",
        // "share",
        // "shield-checkmark",
        // "shield-half",
        // "shield",
        // "shirt",
        // "shuffle",
        // "skull",
        // "snow",
        // "sparkles",
        // "speedometer",
        // "square",
        // "star-half",
        // "star",
        // "stats-chart",
        // "stop-circle",
        // "stop",
        // "stopwatch",
        // "storefront",
        // "subway",
        // "sunny",
        // "swap-horizontal",
        // "swap-vertical",
        // "sync-circle",
        // "sync",
        // "tablet-landscape",
        // "tablet-portrait",
        // "telescope",
        // "tennisball",
        // "terminal",
        // "text",
        // "thermometer",
        // "thumbs-down",
        // "thumbs-up",
        // "thunderstorm",
        // "ticket",
        // "time",
        // "timer",
        // "today",
        // "toggle",
        // "trail-sign",
        // "train",
        // "transgender",
        // "trash-bin",
        // "trash",
        // "trending-down",
        // "trending-up",
        // "triangle",
        // "trophy",
        // "tv",
        // "umbrella",
        // "unlink",
        // "videocam-off",
        // "videocam",
        // "volume-high",
        // "volume-low",
        // "volume-medium",
        // "volume-mute",
        // "volume-off",
        // "walk",
        // "wallet",
        // "warning",
        // "watch",
        // "water",
        // "wifi",
        // "wine",
        // "woman",
        // "accessibility-outline",
        // "add-circle-outline",
        // "add-outline",
        // "airplane-outline",
        // "alarm-outline",
        // "albums-outline",
        // "alert-circle-outline",
        // "alert-outline",
        // "american-football-outline",
        // "analytics-outline",
        // "aperture-outline",
        // "apps-outline",
        // "archive-outline",
        // "arrow-back-circle-outline",
        // "arrow-back-outline",
        // "arrow-down-circle-outline",
        // "arrow-down-outline",
        // "arrow-forward-circle-outline",
        // "arrow-forward-outline",
        // "arrow-redo-circle-outline",
        // "arrow-redo-outline",
        // "arrow-undo-circle-outline",
        // "arrow-undo-outline",
        // "arrow-up-circle-outline",
        // "arrow-up-outline",
        // "at-circle-outline",
        // "at-outline",
        // "attach-outline",
        // "backspace-outline",
        // "bag-add-outline",
        // "bag-check-outline",
        // "bag-handle-outline",
        // "bag-outline",
        // "bag-remove-outline",
        // "balloon-outline",
        // "ban-outline",
        // "bandage-outline",
        // "bar-chart-outline",
        // "barbell-outline",
        // "barcode-outline",
        // "baseball-outline",
        // "basket-outline",
        // "basketball-outline",
        // "battery-charging-outline",
        // "battery-dead-outline",
        // "battery-full-outline",
        // "battery-half-outline",
        // "beaker-outline",
        // "bed-outline",
        // "beer-outline",
        // "bicycle-outline",
        // "bluetooth-outline",
        // "boat-outline",
        // "body-outline",
        // "bonfire-outline",
        // "book-outline",
        // "bookmark-outline",
        // "bookmarks-outline",
        // "bowling-ball-outline",
        // "briefcase-outline",
        // "browsers-outline",
        // "brush-outline",
        // "bug-outline",
        // "build-outline",
        // "bulb-outline",
        // "bus-outline",
        // "business-outline",
        // "cafe-outline",
        // "calculator-outline",
        // "calendar-clear-outline",
        // "calendar-number-outline",
        // "calendar-outline",
        // "call-outline",
        // "camera-outline",
        // "camera-reverse-outline",
        // "car-outline",
        // "car-sport-outline",
        // "card-outline",
        // "caret-back-circle-outline",
        // "caret-back-outline",
        // "caret-down-circle-outline",
        // "caret-down-outline",
        // "caret-forward-circle-outline",
        // "caret-forward-outline",
        // "caret-up-circle-outline",
        // "caret-up-outline",
        // "cart-outline",
        // "cash-outline",
        // "cellular-outline",
        // "chatbox-ellipses-outline",
        // "chatbox-outline",
        // "chatbubble-ellipses-outline",
        // "chatbubble-outline",
        // "chatbubbles-outline",
        // "checkbox-outline",
        // "checkmark-circle-outline",
        // "checkmark-done-circle-outline",
        // "checkmark-done-outline",
        // "checkmark-outline",
        // "chevron-back-circle-outline",
        // "chevron-back-outline",
        // "chevron-double-back-outline",
        // "chevron-double-forward-outline",
        // "chevron-down-circle-outline",
        // "chevron-down-outline",
        // "chevron-forward-circle-outline",
        // "chevron-forward-outline",
        // "chevron-up-circle-outline",
        // "chevron-up-outline",
        // "clipboard-outline",
        // "close-circle-outline",
        // "close-outline",
        // "cloud-circle-outline",
        // "cloud-done-outline",
        // "cloud-download-outline",
        // "cloud-offline-outline",
        // "cloud-outline",
        // "cloud-upload-outline",
        // "cloudy-night-outline",
        // "cloudy-outline",
        // "code-download-outline",
        // "code-outline",
        // "code-slash-outline",
        // "code-working-outline",
        // "cog-outline",
        // "color-fill-outline",
        // "color-filter-outline",
        // "color-palette-outline",
        // "color-wand-outline",
        // "compass-outline",
        // "construct-outline",
        // "contract-outline",
        // "contrast-outline",
        // "copy-outline",
        // "create-outline",
        // "crop-outline",
        // "cube-outline",
        // "cut-outline",
        // "desktop-outline",
        // "diamond-outline",
        // "dice-outline",
        // "disc-outline",
        // "document-attach-outline",
        // "document-lock-outline",
        // "document-outline",
        // "document-text-outline",
        // "documents-outline",
        // "download-outline",
        // "duplicate-outline",
        // "ear-outline",
        // "earth-outline",
        // "easel-outline",
        // "egg-outline",
        // "ellipse-outline",
        // "ellipsis-horizontal-circle-outline",
        // "ellipsis-horizontal-outline",
        // "ellipsis-vertical-circle-outline",
        // "ellipsis-vertical-outline",
        // "enter-outline",
        // "exit-outline",
        // "expand-outline",
        // "extension-puzzle-outline",
        // "eye-off-outline",
        // "eye-outline",
        // "eyedrop-outline",
        // "fast-food-outline",
        // "female-outline",
        // "file-tray-full-outline",
        // "file-tray-outline",
        // "file-tray-stacked-outline",
        // "film-outline",
        // "filter-circle-outline",
        // "filter-outline",
        // "finger-print-outline",
        // "fish-outline",
        // "fitness-outline",
        // "flag-outline",
        // "flame-outline",
        // "flash-off-outline",
        // "flash-outline",
        // "flashlight-outline",
        // "flask-outline",
        // "flower-outline",
        // "folder-open-outline",
        // "folder-outline",
        // "football-outline",
        // "footsteps-outline",
        // "funnel-outline",
        // "game-controller-outline",
        // "gift-outline",
        // "git-branch-outline",
        // "git-commit-outline",
        // "git-compare-outline",
        // "git-merge-outline",
        // "git-network-outline",
        // "git-pull-request-outline",
        // "glasses-outline",
        // "globe-outline",
        // "golf-outline",
        // "grid-outline",
        // "hammer-outline",
        // "hand-left-outline",
        // "hand-right-outline",
        // "happy-outline",
        // "hardware-chip-outline",
        // "headset-outline",
        // "heart-circle-outline",
        // "heart-dislike-circle-outline",
        // "heart-dislike-outline",
        // "heart-half-outline",
        // "heart-outline",
        // "help-buoy-outline",
        // "help-circle-outline",
        // "help-outline",
        // "home-outline",
        // "hourglass-outline",
        // "ice-cream-outline",
        // "id-card-outline",
        // "image-outline",
        // "images-outline",
        // "infinite-outline",
        // "information-circle-outline",
        // "information-outline",
        // "invert-mode-outline",
        // "journal-outline",
        // "key-outline",
        // "keypad-outline",
        // "language-outline",
        // "laptop-outline",
        // "layers-outline",
        // "leaf-outline",
        // "library-outline",
        // "link-outline",
        // "list-circle-outline",
        // "list-outline",
        // "locate-outline",
        // "location-outline",
        // "lock-closed-outline",
        // "lock-open-outline",
        // "log-in-outline",
        // "log-out-outline",
        // "magnet-outline",
        // "mail-open-outline",
        // "mail-outline",
        // "mail-unread-outline",
        // "male-female-outline",
        // "male-outline",
        // "man-outline",
        // "map-outline",
        // "medal-outline",
        // "medical-outline",
        // "medkit-outline",
        // "megaphone-outline",
        // "menu-outline",
        // "mic-circle-outline",
        // "mic-off-circle-outline",
        // "mic-off-outline",
        // "mic-outline",
        // "moon-outline",
        // "move-outline",
        // "musical-note-outline",
        // "musical-notes-outline",
        // "navigate-circle-outline",
        // "navigate-outline",
        // "newspaper-outline",
        // "notifications-circle-outline",
        // "notifications-off-circle-outline",
        // "notifications-off-outline",
        // "notifications-outline",
        // "nuclear-outline",
        // "nutrition-outline",
        // "open-outline",
        // "options-outline",
        // "paper-plane-outline",
        // "partly-sunny-outline",
        // "pause-circle-outline",
        // "pause-outline",
        // "paw-outline",
        // "pencil-outline",
        // "people-circle-outline",
        // "people-outline",
        // "person-add-outline",
        // "person-circle-outline",
        // "person-outline",
        // "person-remove-outline",
        // "phone-landscape-outline",
        // "phone-portrait-outline",
        // "pie-chart-outline",
        // "pin-outline",
        // "pint-outline",
        // "pizza-outline",
        // "planet-outline",
        // "play-back-circle-outline",
        // "play-back-outline",
        // "play-circle-outline",
        // "play-forward-circle-outline",
        // "play-forward-outline",
        // "play-outline",
        // "play-skip-back-circle-outline",
        // "play-skip-back-outline",
        // "play-skip-forward-circle-outline",
        // "play-skip-forward-outline",
        // "podium-outline",
        // "power-outline",
        // "pricetag-outline",
        // "pricetags-outline",
        // "print-outline",
        // "prism-outline",
        // "pulse-outline",
        // "push-outline",
        // "qr-code-outline",
        // "radio-button-off-outline",
        // "radio-button-on-outline",
        // "radio-outline",
        // "rainy-outline",
        // "reader-outline",
        // "receipt-outline",
        // "recording-outline",
        // "refresh-circle-outline",
        // "refresh-outline",
        // "reload-circle-outline",
        // "reload-outline",
        // "remove-circle-outline",
        // "remove-outline",
        // "reorder-four-outline",
        // "reorder-three-outline",
        // "reorder-two-outline",
        // "repeat-outline",
        // "resize-outline",
        // "restaurant-outline",
        // "return-down-back-outline",
        // "return-down-forward-outline",
        // "return-up-back-outline",
        // "return-up-forward-outline",
        // "ribbon-outline",
        // "rocket-outline",
        // "rose-outline",
        // "sad-outline",
        // "save-outline",
        // "scale-outline",
        // "scan-circle-outline",
        // "scan-outline",
        // "school-outline",
        // "search-circle-outline",
        // "search-outline",
        // "send-outline",
        // "server-outline",
        // "settings-outline",
        // "shapes-outline",
        // "share-outline",
        // "share-social-outline",
        // "shield-checkmark-outline",
        // "shield-half-outline",
        // "shield-outline",
        // "shirt-outline",
        // "shuffle-outline",
        // "skull-outline",
        // "snow-outline",
        // "sparkles-outline",
        // "speedometer-outline",
        // "square-outline",
        // "star-half-outline",
        // "star-outline",
        // "stats-chart-outline",
        // "stop-circle-outline",
        // "stop-outline",
        // "stopwatch-outline",
        // "storefront-outline",
        // "subway-outline",
        // "sunny-outline",
        // "swap-horizontal-outline",
        // "swap-vertical-outline",
        // "sync-circle-outline",
        // "sync-outline",
        // "tablet-landscape-outline",
        // "tablet-portrait-outline",
        // "telescope-outline",
        // "tennisball-outline",
        // "terminal-outline",
        // "text-outline",
        // "thermometer-outline",
        // "thumbs-down-outline",
        // "thumbs-up-outline",
        // "thunderstorm-outline",
        // "ticket-outline",
        // "time-outline",
        // "timer-outline",
        // "today-outline",
        // "toggle-outline",
        // "trail-sign-outline",
        // "train-outline",
        // "transgender-outline",
        // "trash-bin-outline",
        // "trash-outline",
        // "trending-down-outline",
        // "trending-up-outline",
        // "triangle-outline",
        // "trophy-outline",
        // "tv-outline",
        // "umbrella-outline",
        // "unlink-outline",
        // "videocam-off-outline",
        // "videocam-outline",
        // "volume-high-outline",
        // "volume-low-outline",
        // "volume-medium-outline",
        // "volume-mute-outline",
        // "volume-off-outline",
        // "walk-outline",
        // "wallet-outline",
        // "warning-outline",
        // "watch-outline",
        // "water-outline",
        // "wifi-outline",
        // "wine-outline",
        // "woman-outline",
      ],
      filledIcon: [
        "accessibility",
        "add-circle",
        "add",
        "airplane",
        "alarm",
        "albums",
        "alert-circle",
        "alert",
        "american-football",
        "analytics",
        "aperture",
        "apps",
        "archive",
        "arrow-back-circle",
        "arrow-back",
        "arrow-down-circle",
        "arrow-down",
        "arrow-forward-circle",
        "arrow-forward",
        "arrow-redo-circle",
        "arrow-redo",
        "arrow-undo-circle",
        "arrow-undo",
        "arrow-up-circle",
        // "arrow-up",
        // "at-circle",
        // "at",
        // "attach",
        // "backspace",
        // "bag-add",
        // "bag-check",
        // "bag-handle",
        // "bag-remove",
        // "bag",
        // "balloon",
        // "ban",
        // "bandage",
        // "bar-chart",
        // "barbell",
        // "barcode",
        // "baseball",
        // "basket",
        // "basketball",
        // "battery-charging",
        // "battery-dead",
        // "battery-full",
        // "battery-half",
        // "beaker",
        // "bed",
        // "beer",
        // "bicycle",
        // "bluetooth",
        // "boat",
        // "body",
        // "bonfire",
        // "book",
        // "bookmark",
        // "bookmarks",
        // "bowling-ball",
        // "briefcase",
        // "browsers",
        // "brush",
        // "bug",
        // "build",
        // "bulb",
        // "bus",
        // "business",
        // "cafe",
        // "calculator",
        // "calendar-clear",
        // "calendar-number",
        // "calendar",
        // "call",
        // "camera-reverse",
        // "camera",
        // "car-sport",
        // "car",
        // "card",
        // "caret-back-circle",
        // "caret-back",
        // "caret-down-circle",
        // "caret-down",
        // "caret-forward-circle",
        // "caret-forward",
        // "caret-up-circle",
        // "caret-up",
        // "cart",
        // "cash",
        // "cellular",
        // "chatbox-ellipses",
        // "chatbox",
        // "chatbubble-ellipses",
        // "chatbubble",
        // "chatbubbles",
        // "checkbox",
        // "checkmark-circle",
        // "checkmark-done-circle",
        // "checkmark-done",
        // "checkmark",
        // "chevron-back-circle",
        // "chevron-back",
        // "chevron-double-back",
        // "chevron-double-forward",
        // "chevron-down-circle",
        // "chevron-down",
        // "chevron-forward-circle",
        // "chevron-forward",
        // "chevron-up-circle",
        // "chevron-up",
        // "clipboard",
        // "close-circle",
        // "close",
        // "cloud-circle",
        // "cloud-done",
        // "cloud-download",
        // "cloud-offline",
        // "cloud-upload",
        // "cloud",
        // "cloudy-night",
        // "cloudy",
        // "code-download",
        // "code-slash",
        // "code-working",
        // "code",
        // "cog",
        // "color-fill",
        // "color-filter",
        // "color-palette",
        // "color-wand",
        // "compass",
        // "construct",
        // "contract",
        // "contrast",
        // "copy",
        // "create",
        // "crop",
        // "cube",
        // "cut",
        // "desktop",
        // "diamond",
        // "dice",
        // "disc",
        // "document-attach",
        // "document-lock",
        // "document-text",
        // "document",
        // "documents",
        // "download",
        // "duplicate",
        // "ear",
        // "earth",
        // "easel",
        // "egg",
        // "ellipse",
        // "ellipsis-horizontal-circle",
        // "ellipsis-horizontal",
        // "ellipsis-vertical-circle",
        // "ellipsis-vertical",
        // "enter",
        // "exit",
        // "expand",
        // "extension-puzzle",
        // "eye-off",
        // "eye",
        // "eyedrop",
        // "fast-food",
        // "female",
        // "file-tray-full",
        // "file-tray-stacked",
        // "file-tray",
        // "film",
        // "filter-circle",
        // "filter",
        // "finger-print",
        // "fish",
        // "fitness",
        // "flag",
        // "flame",
        // "flash-off",
        // "flash",
        // "flashlight",
        // "flask",
        // "flower",
        // "folder-open",
        // "folder",
        // "football",
        // "footsteps",
        // "funnel",
        // "game-controller",
        // "gift",
        // "git-branch",
        // "git-commit",
        // "git-compare",
        // "git-merge",
        // "git-network",
        // "git-pull-request",
        // "glasses",
        // "globe",
        // "golf",
        // "grid",
        // "hammer",
        // "hand-left",
        // "hand-right",
        // "happy",
        // "hardware-chip",
        // "headset",
        // "heart-circle",
        // "heart-dislike-circle",
        // "heart-dislike",
        // "heart-half",
        // "heart",
        // "help-buoy",
        // "help-circle",
        // "help",
        // "home",
        // "hourglass",
        // "ice-cream",
        // "id-card",
        // "image",
        // "images",
        // "infinite",
        // "information-circle",
        // "information",
        // "invert-mode",
        // "journal",
        // "key",
        // "keypad",
        // "language",
        // "laptop",
        // "layers",
        // "leaf",
        // "library",
        // "link",
        // "list-circle",
        // "list",
        // "locate",
        // "location",
        // "lock-closed",
        // "lock-open",
        // "log-in",
        // "log-out",
        // "logo-alipay",
        // "logo-amazon",
        // "logo-amplify",
        // "logo-android",
        // "logo-angular",
        // "logo-apple-appstore",
        // "logo-apple-ar",
        // "logo-apple",
        // "logo-behance",
        // "logo-bitbucket",
        // "logo-bitcoin",
        // "logo-buffer",
        // "logo-capacitor",
        // "logo-chrome",
        // "logo-closed-captioning",
        // "logo-codepen",
        // "logo-css3",
        // "logo-designernews",
        // "logo-deviantart",
        // "logo-discord",
        // "logo-docker",
        // "logo-dribbble",
        // "logo-dropbox",
        // "logo-edge",
        // "logo-electron",
        // "logo-euro",
        // "logo-facebook",
        // "logo-figma",
        // "logo-firebase",
        // "logo-firefox",
        // "logo-flickr",
        // "logo-foursquare",
        // "logo-gitee",
        // "logo-github",
        // "logo-gitlab",
        // "logo-google-playstore",
        // "logo-google",
        // "logo-hackernews",
        // "logo-html5",
        // "logo-instagram",
        // "logo-ionic",
        // "logo-ionitron",
        // "logo-javascript",
        // "logo-kui",
        // "logo-laravel",
        // "logo-linkedin",
        // "logo-markdown",
        // "logo-mastodon",
        // "logo-medium",
        // "logo-microsoft",
        // "logo-no-smoking",
        // "logo-nodejs",
        // "logo-npm",
        // "logo-octocat",
        // "logo-paypal",
        // "logo-pinterest",
        // "logo-playstation",
        // "logo-pwa",
        // "logo-python",
        // "logo-react",
        // "logo-reddit",
        // "logo-rss",
        // "logo-sass",
        // "logo-skype",
        // "logo-slack",
        // "logo-snapchat",
        // "logo-soundcloud",
        // "logo-stackoverflow",
        // "logo-steam",
        // "logo-stencil",
        // "logo-tableau",
        // "logo-telegram",
        // "logo-tiktok",
        // "logo-tumblr",
        // "logo-tux",
        // "logo-twitch",
        // "logo-twitter",
        // "logo-usd",
        // "logo-venmo",
        // "logo-vercel",
        // "logo-vimeo",
        // "logo-vk",
        // "logo-vue",
        // "logo-web-component",
        // "logo-wechat",
        // "logo-whatsapp",
        // "logo-windows",
        // "logo-wordpress",
        // "logo-xbox",
        // "logo-xing",
        // "logo-yahoo",
        // "logo-yen",
        // "logo-youtube",
        // "magnet",
        // "mail-open",
        // "mail-unread",
        // "mail",
        // "male-female",
        // "male",
        // "man",
        // "map",
        // "medal",
        // "medical",
        // "medkit",
        // "megaphone",
        // "menu",
        // "mic-circle",
        // "mic-off-circle",
        // "mic-off",
        // "mic",
        // "moon",
        // "move",
        // "musical-note",
        // "musical-notes",
        // "navigate-circle",
        // "navigate",
        // "newspaper",
        // "notifications-circle",
        // "notifications-off-circle",
        // "notifications-off",
        // "notifications",
        // "nuclear",
        // "nutrition",
        // "open",
        // "options",
        // "paper-plane",
        // "partly-sunny",
        // "pause-circle",
        // "pause",
        // "paw",
        // "pencil",
        // "people-circle",
        // "people",
        // "person-add",
        // "person-circle",
        // "person-remove",
        // "person",
        // "phone-landscape",
        // "phone-portrait",
        // "pie-chart",
        // "pin",
        // "pint",
        // "pizza",
        // "planet",
        // "play-back-circle",
        // "play-back",
        // "play-circle",
        // "play-forward-circle",
        // "play-forward",
        // "play-skip-back-circle",
        // "play-skip-back",
        // "play-skip-forward-circle",
        // "play-skip-forward",
        // "play",
        // "podium",
        // "power",
        // "pricetag",
        // "pricetags",
        // "print",
        // "prism",
        // "pulse",
        // "push",
        // "qr-code",
        // "radio-button-off",
        // "radio-button-on",
        // "radio",
        // "rainy",
        // "reader",
        // "receipt",
        // "recording",
        // "refresh-circle",
        // "refresh",
        // "reload-circle",
        // "reload",
        // "remove-circle",
        // "remove",
        // "reorder-four",
        // "reorder-three",
        // "reorder-two",
        // "repeat",
        // "resize",
        // "restaurant",
        // "return-down-back",
        // "return-down-forward",
        // "return-up-back",
        // "return-up-forward",
        // "ribbon",
        // "rocket",
        // "rose",
        // "sad",
        // "save",
        // "scale",
        // "scan-circle",
        // "scan",
        // "school",
        // "search-circle",
        // "search",
        // "send",
        // "server",
        // "settings",
        // "shapes",
        // "share-social",
        // "share",
        // "shield-checkmark",
        // "shield-half",
        // "shield",
        // "shirt",
        // "shuffle",
        // "skull",
        // "snow",
        // "sparkles",
        // "speedometer",
        // "square",
        // "star-half",
        // "star",
        // "stats-chart",
        // "stop-circle",
        // "stop",
        // "stopwatch",
        // "storefront",
        // "subway",
        // "sunny",
        // "swap-horizontal",
        // "swap-vertical",
        // "sync-circle",
        // "sync",
        // "tablet-landscape",
        // "tablet-portrait",
        // "telescope",
        // "tennisball",
        // "terminal",
        // "text",
        // "thermometer",
        // "thumbs-down",
        // "thumbs-up",
        // "thunderstorm",
        // "ticket",
        // "time",
        // "timer",
        // "today",
        // "toggle",
        // "trail-sign",
        // "train",
        // "transgender",
        // "trash-bin",
        // "trash",
        // "trending-down",
        // "trending-up",
        // "triangle",
        // "trophy",
        // "tv",
        // "umbrella",
        // "unlink",
        // "videocam-off",
        // "videocam",
        // "volume-high",
        // "volume-low",
        // "volume-medium",
        // "volume-mute",
        // "volume-off",
        // "walk",
        // "wallet",
        // "warning",
        // "watch",
        // "water",
        // "wifi",
        // "wine",
        // "woman",
      ],
      outhlineIcon: [
        "accessibility-outline",
        "add-circle-outline",
        "add-outline",
        "airplane-outline",
        "alarm-outline",
        "albums-outline",
        "alert-circle-outline",
        "alert-outline",
        "american-football-outline",
        "analytics-outline",
        "aperture-outline",
        "apps-outline",
        "archive-outline",
        "arrow-back-circle-outline",
        "arrow-back-outline",
        "arrow-down-circle-outline",
        "arrow-down-outline",
        "arrow-forward-circle-outline",
        "arrow-forward-outline",
        "arrow-redo-circle-outline",
        "arrow-redo-outline",
        "arrow-undo-circle-outline",
        "arrow-undo-outline",
        "arrow-up-circle-outline",
        // "arrow-up-outline",
        // "at-circle-outline",
        // "at-outline",
        // "attach-outline",
        // "backspace-outline",
        // "bag-add-outline",
        // "bag-check-outline",
        // "bag-handle-outline",
        // "bag-outline",
        // "bag-remove-outline",
        // "balloon-outline",
        // "ban-outline",
        // "bandage-outline",
        // "bar-chart-outline",
        // "barbell-outline",
        // "barcode-outline",
        // "baseball-outline",
        // "basket-outline",
        // "basketball-outline",
        // "battery-charging-outline",
        // "battery-dead-outline",
        // "battery-full-outline",
        // "battery-half-outline",
        // "beaker-outline",
        // "bed-outline",
        // "beer-outline",
        // "bicycle-outline",
        // "bluetooth-outline",
        // "boat-outline",
        // "body-outline",
        // "bonfire-outline",
        // "book-outline",
        // "bookmark-outline",
        // "bookmarks-outline",
        // "bowling-ball-outline",
        // "briefcase-outline",
        // "browsers-outline",
        // "brush-outline",
        // "bug-outline",
        // "build-outline",
        // "bulb-outline",
        // "bus-outline",
        // "business-outline",
        // "cafe-outline",
        // "calculator-outline",
        // "calendar-clear-outline",
        // "calendar-number-outline",
        // "calendar-outline",
        // "call-outline",
        // "camera-outline",
        // "camera-reverse-outline",
        // "car-outline",
        // "car-sport-outline",
        // "card-outline",
        // "caret-back-circle-outline",
        // "caret-back-outline",
        // "caret-down-circle-outline",
        // "caret-down-outline",
        // "caret-forward-circle-outline",
        // "caret-forward-outline",
        // "caret-up-circle-outline",
        // "caret-up-outline",
        // "cart-outline",
        // "cash-outline",
        // "cellular-outline",
        // "chatbox-ellipses-outline",
        // "chatbox-outline",
        // "chatbubble-ellipses-outline",
        // "chatbubble-outline",
        // "chatbubbles-outline",
        // "checkbox-outline",
        // "checkmark-circle-outline",
        // "checkmark-done-circle-outline",
        // "checkmark-done-outline",
        // "checkmark-outline",
        // "chevron-back-circle-outline",
        // "chevron-back-outline",
        // "chevron-double-back-outline",
        // "chevron-double-forward-outline",
        // "chevron-down-circle-outline",
        // "chevron-down-outline",
        // "chevron-forward-circle-outline",
        // "chevron-forward-outline",
        // "chevron-up-circle-outline",
        // "chevron-up-outline",
        // "clipboard-outline",
        // "close-circle-outline",
        // "close-outline",
        // "cloud-circle-outline",
        // "cloud-done-outline",
        // "cloud-download-outline",
        // "cloud-offline-outline",
        // "cloud-outline",
        // "cloud-upload-outline",
        // "cloudy-night-outline",
        // "cloudy-outline",
        // "code-download-outline",
        // "code-outline",
        // "code-slash-outline",
        // "code-working-outline",
        // "cog-outline",
        // "color-fill-outline",
        // "color-filter-outline",
        // "color-palette-outline",
        // "color-wand-outline",
        // "compass-outline",
        // "construct-outline",
        // "contract-outline",
        // "contrast-outline",
        // "copy-outline",
        // "create-outline",
        // "crop-outline",
        // "cube-outline",
        // "cut-outline",
        // "desktop-outline",
        // "diamond-outline",
        // "dice-outline",
        // "disc-outline",
        // "document-attach-outline",
        // "document-lock-outline",
        // "document-outline",
        // "document-text-outline",
        // "documents-outline",
        // "download-outline",
        // "duplicate-outline",
        // "ear-outline",
        // "earth-outline",
        // "easel-outline",
        // "egg-outline",
        // "ellipse-outline",
        // "ellipsis-horizontal-circle-outline",
        // "ellipsis-horizontal-outline",
        // "ellipsis-vertical-circle-outline",
        // "ellipsis-vertical-outline",
        // "enter-outline",
        // "exit-outline",
        // "expand-outline",
        // "extension-puzzle-outline",
        // "eye-off-outline",
        // "eye-outline",
        // "eyedrop-outline",
        // "fast-food-outline",
        // "female-outline",
        // "file-tray-full-outline",
        // "file-tray-outline",
        // "file-tray-stacked-outline",
        // "film-outline",
        // "filter-circle-outline",
        // "filter-outline",
        // "finger-print-outline",
        // "fish-outline",
        // "fitness-outline",
        // "flag-outline",
        // "flame-outline",
        // "flash-off-outline",
        // "flash-outline",
        // "flashlight-outline",
        // "flask-outline",
        // "flower-outline",
        // "folder-open-outline",
        // "folder-outline",
        // "football-outline",
        // "footsteps-outline",
        // "funnel-outline",
        // "game-controller-outline",
        // "gift-outline",
        // "git-branch-outline",
        // "git-commit-outline",
        // "git-compare-outline",
        // "git-merge-outline",
        // "git-network-outline",
        // "git-pull-request-outline",
        // "glasses-outline",
        // "globe-outline",
        // "golf-outline",
        // "grid-outline",
        // "hammer-outline",
        // "hand-left-outline",
        // "hand-right-outline",
        // "happy-outline",
        // "hardware-chip-outline",
        // "headset-outline",
        // "heart-circle-outline",
        // "heart-dislike-circle-outline",
        // "heart-dislike-outline",
        // "heart-half-outline",
        // "heart-outline",
        // "help-buoy-outline",
        // "help-circle-outline",
        // "help-outline",
        // "home-outline",
        // "hourglass-outline",
        // "ice-cream-outline",
        // "id-card-outline",
        // "image-outline",
        // "images-outline",
        // "infinite-outline",
        // "information-circle-outline",
        // "information-outline",
        // "invert-mode-outline",
        // "journal-outline",
        // "key-outline",
        // "keypad-outline",
        // "language-outline",
        // "laptop-outline",
        // "layers-outline",
        // "leaf-outline",
        // "library-outline",
        // "link-outline",
        // "list-circle-outline",
        // "list-outline",
        // "locate-outline",
        // "location-outline",
        // "lock-closed-outline",
        // "lock-open-outline",
        // "log-in-outline",
        // "log-out-outline",
        // "magnet-outline",
        // "mail-open-outline",
        // "mail-outline",
        // "mail-unread-outline",
        // "male-female-outline",
        // "male-outline",
        // "man-outline",
        // "map-outline",
        // "medal-outline",
        // "medical-outline",
        // "medkit-outline",
        // "megaphone-outline",
        // "menu-outline",
        // "mic-circle-outline",
        // "mic-off-circle-outline",
        // "mic-off-outline",
        // "mic-outline",
        // "moon-outline",
        // "move-outline",
        // "musical-note-outline",
        // "musical-notes-outline",
        // "navigate-circle-outline",
        // "navigate-outline",
        // "newspaper-outline",
        // "notifications-circle-outline",
        // "notifications-off-circle-outline",
        // "notifications-off-outline",
        // "notifications-outline",
        // "nuclear-outline",
        // "nutrition-outline",
        // "open-outline",
        // "options-outline",
        // "paper-plane-outline",
        // "partly-sunny-outline",
        // "pause-circle-outline",
        // "pause-outline",
        // "paw-outline",
        // "pencil-outline",
        // "people-circle-outline",
        // "people-outline",
        // "person-add-outline",
        // "person-circle-outline",
        // "person-outline",
        // "person-remove-outline",
        // "phone-landscape-outline",
        // "phone-portrait-outline",
        // "pie-chart-outline",
        // "pin-outline",
        // "pint-outline",
        // "pizza-outline",
        // "planet-outline",
        // "play-back-circle-outline",
        // "play-back-outline",
        // "play-circle-outline",
        // "play-forward-circle-outline",
        // "play-forward-outline",
        // "play-outline",
        // "play-skip-back-circle-outline",
        // "play-skip-back-outline",
        // "play-skip-forward-circle-outline",
        // "play-skip-forward-outline",
        // "podium-outline",
        // "power-outline",
        // "pricetag-outline",
        // "pricetags-outline",
        // "print-outline",
        // "prism-outline",
        // "pulse-outline",
        // "push-outline",
        // "qr-code-outline",
        // "radio-button-off-outline",
        // "radio-button-on-outline",
        // "radio-outline",
        // "rainy-outline",
        // "reader-outline",
        // "receipt-outline",
        // "recording-outline",
        // "refresh-circle-outline",
        // "refresh-outline",
        // "reload-circle-outline",
        // "reload-outline",
        // "remove-circle-outline",
        // "remove-outline",
        // "reorder-four-outline",
        // "reorder-three-outline",
        // "reorder-two-outline",
        // "repeat-outline",
        // "resize-outline",
        // "restaurant-outline",
        // "return-down-back-outline",
        // "return-down-forward-outline",
        // "return-up-back-outline",
        // "return-up-forward-outline",
        // "ribbon-outline",
        // "rocket-outline",
        // "rose-outline",
        // "sad-outline",
        // "save-outline",
        // "scale-outline",
        // "scan-circle-outline",
        // "scan-outline",
        // "school-outline",
        // "search-circle-outline",
        // "search-outline",
        // "send-outline",
        // "server-outline",
        // "settings-outline",
        // "shapes-outline",
        // "share-outline",
        // "share-social-outline",
        // "shield-checkmark-outline",
        // "shield-half-outline",
        // "shield-outline",
        // "shirt-outline",
        // "shuffle-outline",
        // "skull-outline",
        // "snow-outline",
        // "sparkles-outline",
        // "speedometer-outline",
        // "square-outline",
        // "star-half-outline",
        // "star-outline",
        // "stats-chart-outline",
        // "stop-circle-outline",
        // "stop-outline",
        // "stopwatch-outline",
        // "storefront-outline",
        // "subway-outline",
        // "sunny-outline",
        // "swap-horizontal-outline",
        // "swap-vertical-outline",
        // "sync-circle-outline",
        // "sync-outline",
        // "tablet-landscape-outline",
        // "tablet-portrait-outline",
        // "telescope-outline",
        // "tennisball-outline",
        // "terminal-outline",
        // "text-outline",
        // "thermometer-outline",
        // "thumbs-down-outline",
        // "thumbs-up-outline",
        // "thunderstorm-outline",
        // "ticket-outline",
        // "time-outline",
        // "timer-outline",
        // "today-outline",
        // "toggle-outline",
        // "trail-sign-outline",
        // "train-outline",
        // "transgender-outline",
        // "trash-bin-outline",
        // "trash-outline",
        // "trending-down-outline",
        // "trending-up-outline",
        // "triangle-outline",
        // "trophy-outline",
        // "tv-outline",
        // "umbrella-outline",
        // "unlink-outline",
        // "videocam-off-outline",
        // "videocam-outline",
        // "volume-high-outline",
        // "volume-low-outline",
        // "volume-medium-outline",
        // "volume-mute-outline",
        // "volume-off-outline",
        // "walk-outline",
        // "wallet-outline",
        // "warning-outline",
        // "watch-outline",
        // "water-outline",
        // "wifi-outline",
        // "wine-outline",
        // "woman-outline",
      ],
    };
  },
  created(){
    setTimeout(()=>{
      console.log('12')
    },1000)
  },
  async mounted() {
    this.icon =
      this.iconType == "Filled"
        ? this.filledIcon
        : this.iconType == "Outhline"
        ? this.outhlineIcon
        : this.allIcon;
  },
  methods: {
    iconTypeChange(Radio) {
      if (this.iconType == "Filled") {
        this.icon = this.filledIcon;
      }
      if (this.iconType == "Outhline") {
        this.icon = this.outhlineIcon;
      }
    },
    searchIconVal: debounce(function () {
      if (typeof this.searchText == "string" && this.searchText.length > 0) {
        // 需要做查询的字符串，去空格
        const srt = this.searchText.replace(/\s/g, "");
        // 改造字符串
        const reg = new RegExp(srt, "i");
        if (this.iconType == "Filled") {
          this.icon = this.filledIcon.filter((item) => {
            return reg.test(item);
          });
        }
        if (this.iconType == "Outhline") {
          this.icon = this.outhlineIcon.filter((item) => {
            return reg.test(item);
          });
        }
      } else {
        this.iconTypeChange();
      }
    }, 500),
    copeIcon(icon) {
      let oInput = document.createElement("input");
      oInput.value = icon;
      document.body.appendChild(oInput);
      oInput.select(); // 选择对象;
      document.execCommand("Copy");
      oInput.remove();
      this.$Message.success("复制成功");
    },
  },
};
</script>
<style scoped lang="scss">
.iconBox {
  .searchBox {
    .input {
      width: 50%;
      height: 40px;
      margin-left: 50%;
      transform: translateX(-50%);
      margin-top: 100px;
      margin-bottom: 50px;
    }
    .radioGroup {
      margin-bottom: 100px;
      width: 195px;
      display: block;
      margin-left: 50%;
      transform: translateX(-50%);
    }
  }
  .iconList {
    display: grid;
    grid-gap: 20px 20px;
    justify-content: center;
    grid-template-columns: repeat(auto-fill, 180px);
    .icon {
      height: 80px;
      width: 180px;
      padding-top: 15px;
      .iconFont {
        width: 50px;
        height: 35px;
        margin-left: 50%;
        transform: translateX(-50%);
      }
      .iconName {
        height: 20px;
        line-height: 20px;
        width: 100%;
        text-align: center;
      }
      &:focus,
      &:hover {
        @include color("primary");
        transition: all 0.3s;
        box-shadow: 0 0 7px rgb(97, 97, 97, 0.5);
      }
    }
  }
}
</style>
